// const friends = ['farruk', 'emon', 'sharif', 'saiful'];

// for(const friend of friends){
//     console.log(friend);
// }

// for(let i = 0; i < friends.length; i++){
//     console.log(i);
//     console.log(friends[i])
// }

// const numbers = [39,45,34,23,354,45,34,234,23];
//  for(let i = 0; i < numbers.length; i++){
//     console.log(numbers[i]);
//  }

const numbers = [39,45,34,23,354,45,34,234,23];

let i = 0;
while(i < numbers.lenght){
    console.log(numbers[i]);
    i++;
}
